current_computer: "docker"
type: "CC"
class_list: ["N", "H", "C"]
state: "new"
generation: 0
gen_type: False

computers:
    docker:
        file_paths:
            OPENSLIDE_PATH: "/workspace/openslide"
            HCC_100WTC_model_path: "/workspace/Data/Results/HCC_NDPI/100WTC_Result/100WTC_DB_8_1_1_Model.ckpt"
            HCC_40WTC_model_path: "/workspace/Data/Results/HCC_NDPI/40WTC_Result/40WTC_DB_8_1_1.ckpt"
            CC_40WTC_model_path: "/workspace/Data/Results/CC_NDPI/40WTC_Result"
            test_model: "self"
            # use in 100WTC new HCC_wsis: [1, 6, 8, 9, 13, 16, 27, 29, 30]
            # == 110, 112, 115, 122, 127, 129, 130, 135, 136, 138, 139, 140, 141, 142, 144

            # HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
            # HCC_old_wsis: [1, 12, 22, 33, 45, 56, 67, 76, 89, 91]
            # HCC_old_wsis: [2, 21, 50, 69, 81]
            # HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 41, 42, 43, 44]
            # HCC_old_wsis: [45, 49, 53, 57, 61, 65, 69, 72, 76, 80 ]
            HCC_old_wsis: []
            HCC_wsis: []
            # HCC_wsis: [19, 21, 24, 31, 36, 38, 39, 44, 45, 47, 48, 49, 50, 51, 53]

            # CC_wsis: [6, 8, 11, 12, 13, 14, 39, 52, 54, 55, 72, 108, 111, 116, 122, 124, 130, 131, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 1, 7, 40, 53, 70, 100, 136, 143, 223, 246] #, 185, 208, 244, 246, 247, 248, 291, 374, 375, 377]
            # CC_wsis: [] #72, 108, 111, 116, 122, 124, 130, 131, 137, 138
            # CC_wsis:  [6, 11, 39, 52, 144]
            # CC_wsis: [2, 41, 69, 90, 110, 123, 134, 177, 190, 201]
            CC_wsis: [223, 246]

            # CC_wsis: [3, 41, 71, 91, 123, 135,177, 192, 207, 222]
            classes: [0, 1, 2]
            # trainer
            num_trial: 1
            data_num: 6400
            num_wsi: 1
            # dataset
            HCC_old_ndpi_path: "/workspace/Data/ndpi/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/workspace/Data/ndpi/New_HCC_WSI_rawdata"
            HCC_new_patches_save_path: "/workspace/Data/Datas/HCC_Patch"
            HCC_old_patches_save_path: "/workspace/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_csv_dir: "/workspace/Data/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            CC_ndpi_path: "/workspace/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/workspace/Data/Datas/CC_Patch"
            CC_csv_dir: "/workspace/Data/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"

            HCC_WTC_result_save_path: "/workspace/Data/Results/HCC_NDPI"
            HCC_pseudo_result_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"

            CC_WTC_result_save_path: "/workspace/Data/Results/CC_NDPI"
            CC_pseudo_result_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"
            Mix_WTC_result_save_path: "/workspace/Data/Results/Mix_NDPI"
            generation_save_path: "/workspace/Data/Results/Mix_NDPI"
    ubuntu_1:
        file_paths:
            HCC_old_wsis: [6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 41, 42, 43, 44, 46, 48, 50, 51, 52]
            HCC_wsis: []
            
            CC_wsis: [6, 8, 11, 12, 13, 14, 39, 52, 54, 55, 72, 108, 111, 116, 122, 124, 130, 131, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 1, 7, 40, 53, 70, 100, 136, 143, 223, 246]
            classes : [0, 1, 2]
            test_model: "self"

            # trainer
            num_trial: 1
            data_num: 3200
            num_wsi: 40

            CC_WTC_result_save_path: "/home/ipmclab/project/Results/CC_NDPI"

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab/WSI Files/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/media/ipmclab/WSI Files/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab/project/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/home/ipmclab/project/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path : "/media/ipmclab/WSI Files/CC_WSI_rawdata"
            CC_patches_save_path: "/home/ipmclab/project/Datas/CC_Patch"
            CC_csv_dir : "/home/ipmclab/project/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/home/ipmclab/project/Results/CC_NDPI/Generation_Training"

            HCC_WTC_result_save_path: "/home/ipmclab/project/Results/HCC_NDPI"
            HCC_pseudo_result_save_path: "/home/ipmclab/project/Results/HCC_NDPI/Generation_Training"

            CC_WTC_result_save_path: "/home/ipmclab/project/Results/CC_NDPI"
            CC_pseudo_result_save_path: "/home/ipmclab/project/Results/CC_NDPI/Generation_Training"
            
            Mix_WTC_result_save_path: "/home/ipmclab/project/Results/Mix_NDPI"
            generation_save_path: "/home/ipmclab/project/Results/Mix_NDPI"