current_computer : "docker"
type: "CC"
class_list: ["N", "H", "C"]
state: "new"
generation: 5
gen_type: False

computers:
    docker:
        file_paths:
            OPENSLIDE_PATH: "/workspace/openslide"
            100WTC_model_path: "/workspace/Data/Results/HCC_NDPI/100WTC_Result/100WTC_DB_8_1_1_Model.ckpt"
            40WTC_model_path: "/workspace/Data/Results/HCC_NDPI/40WTC_Result/40WTC_DB_8_1_1.ckpt"
            # use in 100WTC new HCC_wsis: [1, 6, 8, 9, 13, 16, 27, 29, 30]
            HCC_wsis: []
            # HCC_wsis: [19, 21, 24, 31, 36, 38, 39, 44, 45, 47, 48, 49, 50, 51, 53]
            # == 110, 112, 115, 122, 127, 129, 130, 135, 136, 138, 139, 140, 141, 142, 144
            
            # CC_wsis: [1 ,2, 3, 6, 7, 8, 11, 12, 13, 14, 25, 26, 27, 28, 39, 40, 41, 42, 43, 52, 53, 54, 55, 73, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 108, 109, 110, 111, 116]
            # CC_wsis: [215, 217, 222, 223, 224, 225, 226, 241, 242, 243]
            # CC_wsis: [118, 122, 123, 124, 130, 131, 134, 135, 136, 137, 138]
            # CC_wsis: [1, 2, 3, 6, 7, 8, 11, 12, 13, 14, 39, 40, 41, 42, 52, 53, 54, 55, 69, 70, 71, 72, 73, 91, 100, 108, 111, 116, 122, 123, 124, 130, 131, 134, 136, 137, 138, 143, 144, 147]
            # CC_wsis: [143, 144, 145, 146, 147, 148, 149, 157, 158, 163, 164, 165, 167, 168, 169] 
            CC_wsis: [170, 171, 173, 174, 175, 176, 177, 178, 179, 180, 183, 184, 185, 190, 191, 192, 193, 201, 202, 203, 204, 206, 207, 208]
            classes : [0, 2]
            
            # dataset
            HCC_old_ndpi_path: "/workspace/Data/ndpi/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path : "/workspace/Data/ndpi/New_HCC_WSI_rawdata"
            HCC_new_patches_save_path: "/workspace/Data/Datas/HCC_Patch"
            HCC_old_patches_save_path: "/workspace/Data/Datas/HCC_Old_Patch/Unbalanced"
            HCC_csv_dir : "/workspace/Data/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path : "/workspace/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/workspace/Data/Datas/CC_Patch"
            CC_csv_dir : "/workspace/Data/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"
            
            # trainer
            num_trial : 2
            data_num : 2560
            
            # HCC_2_class_1WTC_result_save_path: "F:/Results/HCC_NDPI/2_class_WTC"
            # HCC_3_class_1WTC_result_save_path: "F:/Results/HCC_NDPI/3_class_WTC"
            HCC_WTC_result_save_path: "/workspace/Data/Results/HCC_NDPI"
            HCC_pseudo_result_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            
            # CC_2_class_1WTC_result_save_path: "F:/Results/CC_NDPI/2_class_WTC"
            # CC_3_class_1WTC_result_save_path: "F:/Results/CC_NDPI/3_class_WTC"
            CC_WTC_result_save_path: "/workspace/Data/Results/CC_NDPI"
            CC_pseudo_result_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"

            Mix_multi_WTC_result_save_path: "/workspace/Data/Results/Mix_NDPI"
            generation_save_path: "/workspace/Data/Results/Mix_NDPI"