current_computer : "ubuntu_2"
type: "HCC"
class_list: ["N", "H", "C"]
state: "old"

computers:
    docker:
        file_paths:
            OPENSLIDE_PATH: "/workspace/openslide"
            100WTC_model_path: "/workspace/Data/Results/HCC_NDPI/100WTC_Result/100WTC_DB_8_1_1_Model.ckpt"
            40WTC_model_path: "/workspace/Data/Results/HCC_NDPI/40WTC_Result/40WTC_DB_8_1_1.ckpt"
            HCC_old_wsis: [25, 55] #13, 16, 18, 23, 24
            # HCC_wsis: [14, 26, 42, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 93, 95, 98, 99, 103, 104, 107, 109, 111, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146, 149, 150, 153, 156, 159, 161, 162, 164, 165, 166, 168, 169]
            HCC_wsis: [] # 104, 184, 207, 223, 60, 63, 77, 89, 107, 120
            # CC_wsis: [138, 165, 180, 184, 201, 202, 204]
            # 165, 146, 158, 163, 164, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 459, 460, 461, 468, 469, 470, 471, 472, 473, 474, 475, 476, 483, 484, 487
            CC_wsis: [15]
            classes : [0, 1]
            
            # dataset
            HCC_old_ndpi_path: "/workspace/Data/ndpi/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path : "/workspace/Data/ndpi/New_HCC_WSI_rawdata"
            # HCC_old_patches_save_path: "/workspace/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            # HCC_old_patches_save_path: "/workspace/Data/Datas/temp"
            HCC_old_patches_save_path: "/workspace/Data/Datas/Data/Old_WSI_final"
            HCC_new_patches_save_path: "/workspace/Data/Datas/HCC_Patch"
            
            HCC_csv_dir : "/workspace/Data/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path : "/workspace/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/workspace/Data/Datas/CC_Patch"
            CC_csv_dir : "/workspace/Data/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"

    ubuntu_1:
        file_paths:
            HCC_old_wsis: []
            HCC_wsis: [14, 26, 42, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 112, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146]
            CC_wsis: [146, 158, 163, 164, 165, 203, 218, 289, 290, 362, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 458, 459, 460, 461, 468, 469, 470, 471, 472]
            classes : [0, 2]

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab/WSI Files/Old_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab/WSI Files/New_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab/project/Datas/ndpi/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab/project/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/home/ipmclab/project/Results/HCC_NDPI/Generation_Training"
            
            # CC_ndpi_path : "/media/ipmclab/WSI Files/CC_WSI_rawdata"
            CC_ndpi_path: "/home/ipmclab/project/Datas/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab/HDD4T-2/CC_Patch"
            CC_csv_dir : "/home/ipmclab/project/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/home/ipmclab/project/Results/CC_NDPI/Generation_Training"

    ubuntu_2:
        file_paths:
            HCC_old_wsis: [1, 2, 3, 4, 5]
            HCC_wsis: [87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 112, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146] #14, 26, 42, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 112, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146]
            # 146, 158, 163, 164, 165, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407
            CC_wsis: [2, 41, 69, 110, 123, 134, 177, 190, 201, 1, 3, 6, 7, 8, 11, 12, 13, 14, 15, 39, 40, 42, 43, 52, 53, 54, 55, 67, 70, 71, 72, 88, 91, 95, 100, 108, 109, 111, 118, 122, 124, 130, 131, 135, 136, 137, 138, 143, 144, 145, 167, 168, 169, 170, 171, 173, 174, 175, 178, 179, 180, 183, 184, 185, 189, 191, 192, 202, 204, 206, 207, 208, 215, 217, 222, 223, 224, 225, 226, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 263, 264, 265, 266, 269, 275, 276, 277, 291, 296, 297, 298, 299, 300, 325, 328, 329, 330, 374, 375]
            # CC_wsis: [131, 138, 165, 180, 184, 201, 202, 203, 204]
            classes : [0, 1]

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab-2/WSI Files/Old_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab-2/WSI Files/New_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab-2/HDD8T/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab-2/HDD8T/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab-2/project/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI/Generation_Training"
            
            # CC_ndpi_path : "/media/ipmclab-2/WSI Files/CC_WSI_rawdata"
            CC_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab-2/HDD8T/CC_Patch"
            CC_csv_dir : "/home/ipmclab-2/project/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/home/ipmclab-2/project/Results/CC_NDPI/Generation_Training"