current_computer : "ubuntu_2"
type: "HCC"
class_list: ["N", "H", "C"]
state: "new"
generation: 0
gen_type: False

computers:
    docker:
        file_paths:
            OPENSLIDE_PATH: "/workspace/openslide"
            100WTC_model_path: "/workspace/Data/Results/HCC_NDPI/100WTC_Result/100WTC_DB_8_1_1_Model.ckpt"
            40WTC_model_path: "/workspace/Data/Results/HCC_NDPI/40WTC_Result/40WTC_DB_8_1_1.ckpt"
            # use in 100WTC new HCC_wsis: [1, 6, 8, 9, 13, 16, 27, 29, 30]
            # HCC_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
            # HCC_wsis: [19, 21, 24, 31, 36, 38, 39, 44, 45, 47, 48, 49, 50, 51, 53]
            # == 110, 112, 115, 122, 127, 129, 130, 135, 136, 138, 139, 140, 141, 142, 144
            HCC_old_wsis: []
            HCC_wsis: []
            
            # CC_wsis: [6, 8, 11, 12, 13, 14, 39, 52, 54, 55, 72, 108, 111, 116, 122, 124, 130, 131, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 1, 7, 40, 53, 70, 100, 136, 143, 223, 246]
            # CC_wsis: [6, 8, 11, 12, 13, 14, 39, 52, 54, 55, 72, 108, 111, 116, 122, 124, 130, 131, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 185, 208, 244, 246, 247, 248, 291, 374, 375, 377]
            # CC_wsis: [215, 217, 222, 223, 224, 225, 226, 241, 242, 243]
            # CC_wsis: [291, 374, 375, 377] #[169, 170, 171, 175, 178, 180, 183, 184, 185, 208]
            CC_wsis: [178, 180, 183, 184, 185, 223, 246]
            classes : [0, 2]
            
            # dataset
            HCC_old_ndpi_path: "/workspace/Data/ndpi/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path : "/workspace/Data/ndpi/New_HCC_WSI_rawdata"
            HCC_new_patches_save_path: "/workspace/Data/Datas/HCC_Patch"
            HCC_old_patches_save_path: "/workspace/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_csv_dir : "/workspace/Data/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path : "/workspace/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/workspace/Data/Datas/CC_Patch"
            CC_csv_dir : "/workspace/Data/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"
            
            # trainer
            num_trial : 2
            data_num : 2560
            
            # HCC_2_class_1WTC_result_save_path: "F:/Results/HCC_NDPI/2_class_WTC"
            # HCC_3_class_1WTC_result_save_path: "F:/Results/HCC_NDPI/3_class_WTC"
            HCC_WTC_result_save_path: "/workspace/Data/Results/HCC_NDPI"
            HCC_pseudo_result_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            
            # CC_2_class_1WTC_result_save_path: "F:/Results/CC_NDPI/2_class_WTC"
            # CC_3_class_1WTC_result_save_path: "F:/Results/CC_NDPI/3_class_WTC"
            CC_WTC_result_save_path: "/workspace/Data/Results/CC_NDPI"
            CC_pseudo_result_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"

            Mix_multi_WTC_result_save_path: "/workspace/Data/Results/Mix_NDPI"
            generation_save_path: "/workspace/Data/Results/Mix_NDPI"

    ubuntu_1:
        file_paths:
            HCC_old_wsis: [6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 41, 42, 43, 44, 46, 48, 50, 51, 52]
            HCC_wsis: []
            
            CC_wsis: [6, 8, 11, 12, 13, 14, 39, 52, 54, 55, 72, 108, 111, 116, 122, 124, 130, 131, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 1, 7, 40, 53, 70, 100, 136, 143, 223, 246]
            classes : [0, 1, 2]

            # trainer
            num_trial: 1
            data_num: 3200
            num_wsi: 40

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab/WSI Files/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/media/ipmclab/WSI Files/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab/project/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/home/ipmclab/project/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path : "/media/ipmclab/WSI Files/CC_WSI_rawdata"
            CC_patches_save_path: "/home/ipmclab/project/Datas/CC_Patch"
            CC_csv_dir : "/home/ipmclab/project/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/home/ipmclab/project/Results/CC_NDPI/Generation_Training"

            HCC_WTC_result_save_path: "/home/ipmclab/project/Results/HCC_NDPI"
            HCC_pseudo_result_save_path: "/home/ipmclab/project/Results/HCC_NDPI/Generation_Training"

            CC_WTC_result_save_path: "/home/ipmclab/project/Results/CC_NDPI"
            CC_pseudo_result_save_path: "/home/ipmclab/project/Results/CC_NDPI/Generation_Training"
            
            Mix_WTC_result_save_path: "/home/ipmclab/project/Results/Mix_NDPI"
            generation_save_path: "/home/ipmclab/project/Results/Mix_NDPI"
    ubuntu_2:
        file_paths:
            # HCC_old_wsis: [6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 41, 42, 43, 44, 46, 48, 50, 51, 52]
            HCC_old_wsis: []
            HCC_wsis: [9, 19]
            
            # CC_wsis: [6, 8, 11, 12, 13, 14, 39, 52, 54, 55, 72, 108, 111, 116, 122, 124, 130, 131, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 1, 7, 40, 53, 70, 100, 136, 143, 223, 246]
            # CC_wsis: [185, 190, 191, 192, 193, 201, 202, 204, 206, 207, 208, 215, 217, 222, 223, 224, 225, 226, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 261, 263, 264, 265, 266, 267, 269, 275, 276, 277, 288, 291, 296, 374, 375, 377]
            CC_wsis: [] #189, 203, 289, 290, 297] #, 298, 299, 300, 315, 316, 325, 328, 329, 330, 331, 360, 361, 362, 363, 373, 376, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 409, 422, 454, 455, 458, 459, 460, 461, 468, 469, 470, 471, 472, 473]
            classes : [0, 2]

            # trainer
            num_trial: 1
            data_num: 3200
            num_wsi: 40

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab-2/WSI Files/Old_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab-2/WSI Files/New_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/New_HCC_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab-2/HDD8T/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab-2/HDD8T/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab-2/project/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path : "/media/ipmclab-2/WSI Files/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab-2/HDD8T/CC_Patch"
            CC_csv_dir : "/home/ipmclab-2/project/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/home/ipmclab-2/project/Results/CC_NDPI/Generation_Training"

            HCC_WTC_result_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI"
            HCC_pseudo_result_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI/Generation_Training"

            CC_WTC_result_save_path: "/home/ipmclab-2/project/Results/CC_NDPI"
            CC_pseudo_result_save_path: "/home/ipmclab-2/project/Results/CC_NDPI/Generation_Training"
            
            Mix_WTC_result_save_path: "/home/ipmclab-2/project/Results/Mix_NDPI"
            generation_save_path: "/home/ipmclab-2/project/Results/Mix_NDPI"