current_computer: "ubuntu_2"
type: "Mix"
class_list: ["N", "H", "C"]
state: "mix"
generation: 5
gen_type: True

computers:
    docker:
        file_paths:
            OPENSLIDE_PATH: "/workspace/openslide"
            HCC_100WTC_model_path: "/workspace/Data/Results/HCC_NDPI/100WTC_Result/100WTC_DB_8_1_1_Model.ckpt"
            HCC_40WTC_model_path: "/workspace/Data/Results/HCC_NDPI/40WTC_Result/40WTC_DB_8_1_1.ckpt"
            CC_40WTC_model_path: "/workspace/Data/Results/CC_NDPI/40WTC_Result"

            HCC_old_wsis: [1, 2, 3, 4, 5] #, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91]
            # HCC_old_wsis: [45, 49, 53, 57, 61, 65, 69, 72, 76, 80]
            # HCC_wsis: [1, 6, 8, 13, 16, 27, 29 ,30 , 31, 36, 38, 39, 44, 45, 47, 49, 50, 51, 53]
            HCC_wsis: []
            # CC_wsis: [1, 3, 6, 7, 8, 11, 12, 13, 14, 15, 39, 40, 42, 43, 52, 53, 54, 55, 67, 70, 71, 72, 88, 91, 95, 100, 108, 109, 111, 118, 122, 124, 130, 131, 135, 136, 137, 138, 143, 144, 145, 167, 168, 169, 170, 171, 173, 174, 175, 178, 179, 180, 183, 184, 185, 189, 191, 192, 202, 204, 206, 207, 208, 215, 217, 222, 223, 224, 225, 226, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 263, 264, 265, 266, 269, 275, 276, 277, 291, 296, 297, 298, 299, 300, 325, 328, 329, 330, 374, 375]
            # CC_wsis: [2, 41, 69, 90, 110, 123, 134, 177, 190, 201]
            CC_wsis: []
            classes: [0, 1]
            
            test_model: "self"
            test_state: "old"
            test_type: "HCC"

            # trainer
            num_trial: 1
            data_num: "ALL"
            num_wsi: 1
            # dataset
            HCC_old_ndpi_path: "/workspace/Data/ndpi/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/workspace/Data/ndpi/New_HCC_WSI_rawdata"
            HCC_new_patches_save_path: "/workspace/Data/Datas/HCC_Patch"
            HCC_old_patches_save_path: "/workspace/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_csv_dir: "/workspace/Data/Results/HCC_NDPI/Data_Info"
            HCC_WTC_result_save_path: "/workspace/Data/Results/HCC_NDPI"
            HCC_generation_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path: "/workspace/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/workspace/Data/Datas/CC_Patch"
            CC_csv_dir: "/workspace/Data/Results/CC_NDPI/Data_Info"
            CC_WTC_result_save_path: "/workspace/Data/Results/CC_NDPI"
            CC_generation_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"

            Mix_WTC_result_save_path: "/workspace/Data/Results/Mix_NDPI"
            Mix_generation_save_path: "/workspace/Data/Results/Mix_NDPI"
    ubuntu_1:
        file_paths:
            HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 48, 50, 51, 52, 54, 55, 56, 58, 59, 60, 62, 63, 64, 66, 67, 68, 70, 71, 73, 74, 75, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91]
            # HCC_old_wsis: [45, 49, 53, 57, 61, 65, 69, 72, 76, 80]
            HCC_wsis: [1, 6, 8, 13, 16, 27, 29 ,30 , 31, 36, 38, 39, 44, 45, 47, 49, 50, 51, 53]
            # delete: 96, 116, 193, add: 15, 88, 145
            CC_wsis: [1, 3, 6, 7, 8, 11, 12, 13, 14, 15, 39, 40, 42, 43, 52, 53, 54, 55, 67, 70, 71, 72, 88, 91, 95, 100, 108, 109, 111, 118, 122, 124, 130, 131, 135, 136, 137, 138, 143, 144, 145, 167, 168, 169, 170, 171, 173, 174, 175, 178, 179, 180, 183, 184, 185, 189, 191, 192, 202, 204, 206, 207, 208, 215, 217, 222, 223, 224, 225, 226, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 263, 264, 265, 266, 269, 275, 276, 277, 291, 296, 297, 298, 299, 300, 325, 328, 329, 330, 374, 375]
            # CC_wsis: [2, 41, 69, 90, 110, 123, 134, 177, 190, 201]
            classes : [0, 2]
            
            test_model: "self"
            test_state: "new"
            test_type: "CC"

            # trainer
            num_trial: 1
            data_num: 3200
            num_wsi: 1

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab/WSI Files/Old_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab/WSI Files/New_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab/project/Datas/ndpi/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab/project/Results/HCC_NDPI/Data_Info"
            HCC_WTC_result_save_path: "/home/ipmclab/project/Results/HCC_NDPI"
            HCC_generation_save_path: "/home/ipmclab/project/Results/HCC_NDPI/Generation_Training"
            
            # CC_ndpi_path : "/media/ipmclab/WSI Files/CC_WSI_rawdata"
            CC_ndpi_path: "/home/ipmclab/project/Datas/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab/HDD4T-2/CC_Patch"
            CC_csv_dir : "/home/ipmclab/project/Results/CC_NDPI/Data_Info"
            CC_WTC_result_save_path: "/home/ipmclab/project/Results/CC_NDPI"
            CC_generation_save_path: "/home/ipmclab/project/Results/CC_NDPI/Generation_Training"
            
            Mix_WTC_result_save_path: "/home/ipmclab/project/Results/Mix_NDPI"
            Mix_generation_save_path: "/home/ipmclab/project/Results/Mix_NDPI/Generation_Training"
    ubuntu_2:
        file_paths:
            # HCC_old_wsis: [1, 2, 3, 4, 5] #, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 48, 50, 51, 52, 54, 55, 56, 58, 59, 60, 62, 63, 64, 66, 67, 68, 70, 71, 73, 74, 75, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91]
            HCC_old_wsis: [45, 49, 53, 57, 61, 65, 69, 72, 76, 80]
            HCC_wsis: [1, 6, 8, 13, 16, 27, 29 ,30 , 31, 36, 38, 39, 44, 45, 47, 49, 50, 51, 53]
            # HCC_wsis: [14, 26, 42, 53, 56, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 112, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146]
            # delete: 96, 116, 193, add: 15, 88, 145
            # CC_wsis: [1, 3, 6, 7, 8, 11, 12, 13, 14, 15, 39, 40, 42, 43, 52, 53, 54, 55, 67, 70, 71, 72, 88, 91, 95, 100, 108, 109, 111, 118, 122, 124, 130, 131, 135, 136, 137, 138, 143, 144, 145, 167, 168, 169, 170, 171, 173, 174, 175, 178, 179, 180, 183, 184, 185, 189, 191, 192, 202, 204, 206, 207, 208, 215, 217, 222, 223, 224, 225, 226, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 263, 264, 265, 266, 269, 275, 276, 277, 291, 296, 297, 298, 299, 300, 325, 328, 329, 330, 374, 375]
            CC_wsis: [2, 41, 69, 90, 110, 123, 134, 177, 190, 201] #146, 158, 163, 164, 165, 203, 218, 289, 290, 362, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 458, 459, 460, 461, 468, 469, 470, 471, 472]
            classes : [0, 1, 2]

            # trainer
            num_trial: 1
            data_num: 3200
            num_wsi: 100
            test_model: "3_class_100WTC" #"self"
            test_state: "old"
            test_type: "HCC"

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab-2/WSI Files/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/New_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab-2/WSI Files/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab-2/HDD8T/Data/DB_Backup/DB/Unbalenced"
            # HCC_old_patches_save_path: "/media/ipmclab-2/704CB24D4CB20E3A/temp"
            HCC_new_patches_save_path: "/media/ipmclab-2/HDD8T/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab-2/project/Results/HCC_NDPI/Data_Info"
            HCC_WTC_result_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI"
            HCC_generation_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI/Generation_Training"
            
            # CC_ndpi_path : "/media/ipmclab-2/WSI Files/CC_WSI_rawdata"
            CC_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab-2/HDD8T/CC_Patch"
            CC_csv_dir : "/home/ipmclab-2/project/Results/CC_NDPI/Data_Info"
            CC_WTC_result_save_path: "/home/ipmclab-2/project/Results/CC_NDPI"
            CC_generation_save_path: "/home/ipmclab-2/project/Results/CC_NDPI/Generation_Training"
            
            Mix_WTC_result_save_path: "/home/ipmclab-2/project/Results/Mix_NDPI"
            Mix_generation_save_path: "/home/ipmclab-2/project/Results/Mix_NDPI/Generation_Training"

            100WTC_model_path: "/home/ipmclab-2/project/Results/Mix_NDPI/100WTC_Result/LP_3200/trial_1/Model/100WTC_LP3200_3_class_trial_1_Model.ckpt"