current_computer : "computer_1"
type: "HCC"
class_list: ["N", "H", "C"]
state: "new"
generation: 5
gen: True

computers:
    computer_1:
        name: "IPMC-L"                 
        file_paths:
            100WTC_model_path: "F:/Results/HCC_NDPI/100WTC_Result/100WTC_DB_8_1_1_Model.ckpt"
            40WTC_model_path: "F:/Results/HCC_NDPI/40WTC_Result/40WTC_DB_8_1_1.ckpt"
            # HCC_wsis: [1, 6, 8, 9, 13, 16, 19, 27, 29, 30]
            HCC_wsis: [38]
            # CC_wsis: [1 ,2, 3, 6, 7, 8, 11, 53, 54, 55]
            CC_wsis: []
            classes : [0, 1]
            
            # dataset
            HCC_ndpi_path : "F:/Results/HCC_NDPI/HCC_label"
            HCC_patches_save_path: "F:/Datas/Patch"
            HCC_old_patches_save_path: "F:/Datas/HCC_Old_Patch/Unbalanced"
            HCC_csv_dir : "F:/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "F:/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path : "F:/Results/HCC_NDPI/CC_label"
            CC_patches_save_path: "F:/Datas/CC_Patch"
            CC_csv_dir : "F:/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "F:/Results/CC_NDPI/Generation_Training"
            
            # trainer
            num_trial : 1
            data_num : 160
            
            # HCC_2_class_1WTC_result_save_path: "F:/Results/HCC_NDPI/2_class_WTC"
            # HCC_3_class_1WTC_result_save_path: "F:/Results/HCC_NDPI/3_class_WTC"
            HCC_WTC_result_save_path: "F:/Results/HCC_NDPI"
            HCC_pseudo_result_save_path: "F:/Results/HCC_NDPI/Generation_Training"
            
            # CC_2_class_1WTC_result_save_path: "F:/Results/CC_NDPI/2_class_WTC"
            # CC_3_class_1WTC_result_save_path: "F:/Results/CC_NDPI/3_class_WTC"
            CC_WTC_result_save_path: "F:/Results/CC_NDPI"
            CC_pseudo_result_save_path: "F:/Results/CC_NDPI/Generation_Training"

            Mix_multi_WTC_result_save_path: "F:/Results/Mix_NDPI"
            generation_save_path: "F:/Results/Mix_NDPI"


    computer_2:
        name: "DeskTop-LG"
        type:
            CC:
                file_paths:
                    wsis: [67, 68, 69, 70, 71, 72]
                    classes : [1, 2]
                    # dataset
                    ndpi_path : "F:/CC_WSI_rawdata"
                    patches_save_path: "E:/Datas/CC_Patch"
                    csv_dir : "E:/Results/CC_NDPI/Data_Info"
                    generation_save_path: "E:/Results/CC_NDPI/Generation_Training"
                    # trainer
                    num_trial : 1
                    data_num : 160
                    2_class_1WTC_result_save_path: "E:/Results/CC_NDPI/2_class_WTC"
                    3_class_1WTC_result_save_path: "E:/Results/CC_NDPI/3_class_WTC"
                    multi_WTC_result_save_path: "E:/Results/CC_NDPI"
                    pseudo_result_save_path: "E:/Results/CC_NDPI/Generation_Training"


            HCC:
                file_paths:
                    wsis: [16]
                    classes : [0, 2]
                    100WTC_model_path: "E:/Results/HCC_NDPI/100WTC/100WTC_DB_8_1_1_Model.ckpt"
                    40WTC_model_path: "E:/Results/HCC_NDPI/40WTC/40WTC_DB_8_1_1.ckpt"
                    # dataset
                    ndpi_path : "F:/New_HCC_WSI_rawdata"
                    patches_save_path: "E:/Datas/Patch"
                    csv_dir : "E:/Results/HCC_NDPI/Data_Info"
                    generation_save_path: "E:/Results/HCC_NDPI/Generation_Training"
                    # trainer
                    num_trial : 1
                    data_num : 160
                    2_class_1WTC_result_save_path: "E:/Results/HCC_NDPI/2_class_WTC"
                    3_class_1WTC_result_save_path: "E:/Results/HCC_NDPI/3_class_WTC"
                    multi_WTC_result_save_path: "E:/Results/HCC_NDPI"
                    pseudo_result_save_path: "E:/Results/HCC_NDPI/Generation_Training"

            Mix:
                file_paths:
                    HCC_wsis: [1, 6, 8, 9, 13, 16, 19, 27, 29, 30]
                    CC_wsis : [1 ,2, 3, 6, 7, 8, 11, 53, 54, 55]
                    classes : [0, 1, 2]
                    100WTC_model_path: "E:/Results/HCC_NDPI/100WTC/100WTC_DB_8_1_1_Model.ckpt"
                    40WTC_model_path: "E:/Results/HCC_NDPI/40WTC/40WTC_DB_8_1_1.ckpt"
                    # trainer
                    num_trials : [1]
                    data_num : 1280
                    multi_num_wsi: 10
                    HCC_csv_dir : "E:/Results/HCC_NDPI/Data_Info"
                    CC_csv_dir : "E:/Results/CC_NDPI/Data_Info"
                    HCC_patches_save_path: "E:/Datas/Patch"
                    CC_patches_save_path: "E:/Datas/CC_Patch"
                    multi_WTC_result_save_path: "E:/Results/Mix_NDPI"
