current_computer : "docker"
type: "CC"
class_list: ["N", "H", "C"]
state: "new"
generation: 0
gen_type: False

computers:
    docker:
        file_paths:
            OPENSLIDE_PATH: "/workspace/openslide"
            100WTC_model_path: "/workspace/Data/Results/HCC_NDPI/100WTC_Result/100WTC_DB_8_1_1_Model.ckpt"
            40WTC_model_path: "/workspace/Data/Results/HCC_NDPI/40WTC_Result/40WTC_DB_8_1_1.ckpt"
            HCC_old_wsis: []
            HCC_wsis: [14, 26, 42, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 112, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146]
            # okay: 363, 376, 373, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 459, 460, 461, 468
            CC_wsis: [325, 328, 329, 330]
            # CC_wsis: [146, 158, 163, 164, 165, 203, 218, 289, 290, 362, 458, 469, 470, 471, 472]
            classes : [0, 1]
            
            # dataset
            HCC_old_ndpi_path: "/workspace/Data/ndpi/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path : "/workspace/Data/ndpi/New_HCC_WSI_rawdata"
            HCC_new_patches_save_path: "/workspace/Data/Datas/HCC_Patch"
            HCC_old_patches_save_path: "/workspace/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_csv_dir : "/workspace/Data/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path : "/workspace/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/workspace/Data/Datas/CC_Patch"
            CC_csv_dir : "/workspace/Data/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"

    ubuntu_1:
        file_paths:
            HCC_old_wsis: []
            HCC_wsis: [14, 26, 42, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 112, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146]
            CC_wsis: [146, 158, 163, 164, 165, 203, 218, 289, 290, 362, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 458, 459, 460, 461, 468, 469, 470, 471, 472]
            classes : [0, 2]

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab/WSI Files/Old_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab/WSI Files/New_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab/project/Datas/ndpi/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab/project/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/home/ipmclab/project/Results/HCC_NDPI/Generation_Training"
            
            # CC_ndpi_path : "/media/ipmclab/WSI Files/CC_WSI_rawdata"
            CC_ndpi_path: "/home/ipmclab/project/Datas/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab/HDD4T-2/CC_Patch"
            CC_csv_dir : "/home/ipmclab/project/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/home/ipmclab/project/Results/CC_NDPI/Generation_Training"

    ubuntu_2:
        file_paths:
            HCC_old_wsis: []
            # ok: 26
            HCC_wsis: [14, 42, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 112, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146]

            # ok: 158, 163,
            CC_wsis: [46 ,164, 165, 203, 218, 289, 290, 362, 458, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455,  459, 460, 461, 468, 469, 470, 471, 472]
            classes : [0, 2]

            # dataset
            HCC_old_ndpi_path: "/media/ipmclab-2/WSI Files/Old_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab-2/WSI Files/New_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab-2/HDD8T/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab-2/HDD8T/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab-2/project/Results/HCC_NDPI/Data_Info"
            HCC_generation_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI/Generation_Training"
            
            # CC_ndpi_path : "/media/ipmclab-2/WSI Files/CC_WSI_rawdata"
            CC_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab-2/HDD8T/CC_Patch"
            CC_csv_dir : "/home/ipmclab-2/project/Results/CC_NDPI/Data_Info"
            CC_generation_save_path: "/home/ipmclab-2/project/Results/CC_NDPI/Generation_Training"