current_computer: "ubuntu_1"
state: "new"
type: "CC"
class_list: ["N", "H", "C", "NC"]
generation: 5
gen_type: True
patch_size: 448

computers:
    docker:
        file_paths:
            OPENSLIDE_PATH: "/workspace/openslide"
            HCC_100WTC_model_path: "/workspace/Data/Results/HCC_NDPI/100WTC_Result/100WTC_DB_8_1_1_Model.ckpt"
            HCC_40WTC_model_path: "/workspace/Data/Results/HCC_NDPI/40WTC_Result/40WTC_DB_8_1_1.ckpt"
            CC_40WTC_model_path: "/workspace/Data/Results/CC_NDPI/40WTC_Result"

            # small set
            # HCC_old_wsis: [7, 11, 20, 35, 45, 6, 10, 23, 29, 34, 54, 58, 84, 1, 4, 25, 55]
            # 10WTC
            HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
            # 40WTC
            # HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 41, 42, 43, 44]
            # 100WTC
            # HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 48, 50, 51, 52, 54, 55, 56, 58, 59, 60, 62, 63, 64, 66, 67, 68, 70, 71, 73, 74, 75, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91]
            # small testing
            # HCC_old_wsis: [45, 49, 53, 57, 61, 65, 69, 72, 76, 80]
            # empty
            # HCC_old_wsis: []
            
            # small set
            # HCC_wsis: [13, 27, 1]
            # 100WTC
            # HCC_wsis: [1, 6, 8, 13, 16, 27, 29 ,30 , 31, 36, 38, 39, 44, 45, 47, 49, 50, 51, 53]
            # large testing
            # HCC_wsis: [14, 26, 42, 56, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146, 149, 150]
            # empty
            HCC_wsis: []
            
            # small set
            # CC_wsis: [1, 11, 40, 70, 110, 8, 39, 109, 122, 137, 180, 189, 207, 134, 201, 53, 90, 100, 108, 130]
            # 10WTC
            CC_wsis: [1, 3, 6, 7, 8, 11, 12, 13, 14, 15]
            # 40WTC - old version
            # CC_wsis: [1, 6, 7, 8, 11, 12, 13, 14, 39, 40, 52, 53, 54, 55, 70, 72, 100, 108, 111, 118, 122, 124, 130, 131, 136, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 223, 246]
            # 40WTC - new version
            # CC_wsis: [1, 6, 7, 8, 11, 12, 13, 14, 39, 40, 52, 53, 54, 55, 70, 72, 100, 108, 111, 118, 122, 124, 130, 131, 136, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 191, 202]
            # 100WTC
            # CC_wsis: [1, 3, 6, 7, 8, 11, 12, 13, 14, 15, 39, 40, 42, 43, 52, 53, 54, 55, 67, 70, 71, 72, 88, 91, 95, 100, 108, 109, 111, 118, 122, 124, 130, 131, 135, 136, 137, 138, 143, 144, 145, 167, 168, 169, 170, 171, 173, 174, 175, 178, 179, 180, 183, 184, 185, 189, 191, 192, 202, 204, 206, 207, 208, 215, 217, 222, 223, 224, 225, 226, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 263, 264, 265, 266, 269, 275, 276, 277, 291, 296, 297, 298, 299, 300, 325, 328, 329, 330, 374, 375]
            # small testing
            # CC_wsis: [2, 41, 69, 90, 110, 123, 134, 177, 190, 201] #146, 158, 163, 164, 165, 203, 218, 289, 290, 362, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 458, 459, 460, 461, 468, 469, 470, 471, 472]
            # large testing
            # CC_wsis: [146, 158, 163, 164, 165, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 459, 460, 461, 468, 469, 470, 471, 472, 474, 475, 476, 483, 484]
            # empty
            # CC_wsis: []
            
            classes: [0, 1, 2]
            
            # trainer
            num_trial: 2
            data_num: 3200
            num_wsi: 10
            
            backbone: ViT
            pretrain: False
            
            test_model: "self" #self / multi / 3_class_40WTC /3_class_100WTC
            test_state: "old"
            test_type: "HCC"
            test_model_trial: 0
            test_model_wsis: []

            min_epoch: 30
            max_epoch: 30
            max_notImprove: 2
            ema_decay: 0.999

            batch_size: 32
            base_lr: 1e-5

            flip_mode: "connect" # connect / contour
            area_thresh: 20

            # dataset
            error_rate: 0
            load_dataset: False
            data_trial: 0

            HCC_old_ndpi_path: "/workspace/Data/ndpi/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/workspace/Data/ndpi/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/workspace/Data/Datas/Data/Old_WSI_final"
            # HCC_old_patches_save_path: "/workspace/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/workspace/Data/Datas/HCC_Patch"
            HCC_csv_dir: "/workspace/Data/Results/HCC_NDPI/Data_Info"
            HCC_WTC_result_save_path: "/workspace/Data/Results/HCC_NDPI"
            HCC_generation_save_path: "/workspace/Data/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path: "/workspace/Data/ndpi/CC_WSI_rawdata"
            CC_patches_save_path: "/workspace/Data/Datas/CC_Patch"
            CC_csv_dir: "/workspace/Data/Results/CC_NDPI/Data_Info"
            CC_WTC_result_save_path: "/workspace/Data/Results/CC_NDPI"
            CC_generation_save_path: "/workspace/Data/Results/CC_NDPI/Generation_Training"

            Mix_WTC_result_save_path: "/workspace/Data/Results/Mix_NDPI"
            Mix_generation_save_path: "/workspace/Data/Results/Mix_NDPI/Generation_Training"

            40WTC_model_path: "/workspace/Data/Results/Mix_NDPI/40WTC_Result/LP_6400/trial_2/Model/40WTC_LP6400_3_class_trial_2_Model.ckpt"
            100WTC_model_path: "/workspace/Data/Results/Mix_NDPI/100WTC_Result/LP_3200/trial_1/Model/100WTC_LP3200_3_class_trial_1_Model.ckpt"
    ubuntu_1:
        file_paths:
            # small set
            # HCC_old_wsis: [7, 11, 20, 35, 45, 6, 10, 23, 29, 34, 54, 58, 84, 1, 4, 25, 55]
            # 40WTC
            # HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 41, 42, 43, 44]
            # 100WTC
            # HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 48, 50, 51, 52, 54, 55, 56, 58, 59, 60, 62, 63, 64, 66, 67, 68, 70, 71, 73, 74, 75, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91]
            # small testing
            # HCC_old_wsis: [45, 49, 53, 57, 61, 65, 69, 72, 76, 80]
            # empty
            HCC_old_wsis: []
            
            # small set
            # HCC_wsis: [13, 27, 1]
            # 100WTC
            # HCC_wsis: [1, 6, 8, 13, 16, 27, 29 ,30 , 31, 36, 38, 39, 44, 45, 47, 49, 50, 51, 53]
            # large testing
            # HCC_wsis: [14, 26, 42, 56, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146, 149, 150]
            # empty
            HCC_wsis: []
            
            # small set
            # CC_wsis: [1, 11, 40, 70, 110, 8, 39, 109, 122, 137, 180, 189, 207, 134, 201, 53, 90, 100, 108, 130]
            # 40WTC - old version
            # CC_wsis: [1, 6, 7, 8, 11, 12, 13, 14, 39, 40, 52, 53, 54, 55, 70, 72, 100, 108, 111, 118, 122, 124, 130, 131, 136, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 223, 246]
            # 40WTC - new version
            # CC_wsis: [1, 6, 7, 8, 11, 12, 13, 14, 39, 40, 52, 53, 54, 55, 70, 72, 100, 108, 111, 118, 122, 124, 130, 131, 136, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 191, 202]
            # 100WTC
            # CC_wsis: [1, 3, 6, 7, 8, 11, 12, 13, 14, 15, 39, 40, 42, 43, 52, 53, 54, 55, 67, 70, 71, 72, 88, 91, 95, 100, 108, 109, 111, 118, 122, 124, 130, 131, 135, 136, 137, 138, 143, 144, 145, 167, 168, 169, 170, 171, 173, 174, 175, 178, 179, 180, 183, 184, 185, 189, 191, 192, 202, 204, 206, 207, 208, 215, 217, 222, 223, 224, 225, 226, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 263, 264, 265, 266, 269, 275, 276, 277, 291, 296, 297, 298, 299, 300, 325, 328, 329, 330, 374, 375]
            # small testing 
            CC_wsis: [2, 41, 69, 90, 110, 123, 134, 177, 190, 201]
            # large testing
            # CC_wsis: [146, 158, 163, 164, 165, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 459, 460, 461, 468, 469, 470, 471, 472, 474, 475, 476, 483, 484]
            # empty
            # CC_wsis: []
            
            classes : [0, 2]

            old_HCC_shift_map:
                0: [0, 0]
                1: [-15, 10]
                2: [0, 0]

            # trainer
            num_trial: 1
            data_num: ALL
            num_wsi: 40

            backbone: "ViT" # efficient / ViT
            pretrain: False
            
            test_model: "2_class_CC_40WTC" # self / multi / 3_class_40WTC /3_class_100WTC
            test_state: "new"
            test_type: "CC"
            test_model_trial: 0
            test_model_wsis: []

            min_epoch: 5
            max_epoch: 5
            max_notImprove: 2
            ema_decay: 0.999

            batch_size: 32
            base_lr: 1e-5

            flip_mode: "connect"
            area_thresh: 20
            
            # dataset
            error_rate: 0
            load_dataset: False
            data_trial: 0
            
            HCC_old_ndpi_path: "/home/ipmclab/project/Datas/ndpi/Old_HCC_WSI_rawdata"
            # HCC_old_ndpi_path: "/media/ipmclab/WSI Files/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab/project/Datas/ndpi/New_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab/WSI Files/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab/Data_Disk/Data/Datas/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab/project/Results/HCC_NDPI/Data_Info"
            HCC_WTC_result_save_path: "/home/ipmclab/project/Results/HCC_NDPI"
            HCC_generation_save_path: "/home/ipmclab/project/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path: "/home/ipmclab/project/Datas/ndpi/CC_WSI_rawdata"
            # CC_ndpi_path : "/media/ipmclab/WSI Files/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab/HDD4T-2/CC_Patch"
            CC_csv_dir : "/home/ipmclab/project/Results/CC_NDPI/Data_Info"
            CC_WTC_result_save_path: "/home/ipmclab/project/Results/CC_NDPI"
            CC_generation_save_path: "/home/ipmclab/project/Results/CC_NDPI/Generation_Training"
            
            Mix_WTC_result_save_path: "/home/ipmclab/project/Results/Mix_NDPI"
            Mix_generation_save_path: "/home/ipmclab/project/Results/Mix_NDPI/Generation_Training"

            2_class_CC_40WTC_model_path: "/home/ipmclab/project/Results/CC_NDPI/40WTC_Result/LP_3200/trial_4/Model/40WTC_LP3200_2_class_trial_4_Model.ckpt"
            3_class_40WTC_model_path: "/home/ipmclab/project/Results/Mix_NDPI/40WTC_Result/LP_6400/trial_2/Model/40WTC_LP6400_3_class_trial_2_Model.ckpt"
            3_class_100WTC_model_path: "/home/ipmclab/project/Results/Mix_NDPI/100WTC_Result/LP_3200/trial_1/Model/100WTC_LP3200_3_class_trial_1_Model.ckpt"
    ubuntu_2:
        file_paths:
            # small set
            # HCC_old_wsis: [7, 11, 20, 35, 45, 6, 10, 23, 29, 34, 54, 58, 84, 1, 4, 25, 55]
            # HCC_old_wsis: [6, 11, 7, 10, 1, 4]
            # 40WTC
            HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 41, 42, 43, 44]
            # 100WTC
            # HCC_old_wsis: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 48, 50, 51, 52, 54, 55, 56, 58, 59, 60, 62, 63, 64, 66, 67, 68, 70, 71, 73, 74, 75, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91]
            # small testing
            # HCC_old_wsis: [45, 49, 53, 57, 61, 65, 69, 72, 76, 80]
            # empty
            # HCC_old_wsis: []
            
            # small set
            # HCC_wsis: [13, 27, 1]
            # 100WTC
            # HCC_wsis: [1, 6, 8, 13, 16, 27, 29 ,30 , 31, 36, 38, 39, 44, 45, 47, 49, 50, 51, 53]
            # large testing
            # HCC_wsis: [14, 26, 42, 56, 57, 60, 62, 63, 68, 69, 77, 78, 79, 80, 87, 89, 90, 92, 95, 98, 99, 103, 104, 107, 109, 111, 120, 121, 122, 129, 131, 132, 135, 139, 141, 142, 145, 146, 149, 150]
            # empty
            HCC_wsis: []
            
            # small set
            # CC_wsis: [1, 11, 40, 70, 110, 8, 39, 109, 122, 137, 180, 189, 207, 134, 201, 53, 90, 100, 108, 130]
            # CC_wsis: [1, 11, 8, 39, 53, 90]
            # 40WTC - old version
            # CC_wsis: [1, 6, 7, 8, 11, 12, 13, 14, 39, 40, 52, 53, 54, 55, 70, 72, 100, 108, 111, 118, 122, 124, 130, 131, 136, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 223, 246]
            # 40WTC - new version
            CC_wsis: [1, 6, 7, 8, 11, 12, 13, 14, 39, 40, 52, 53, 54, 55, 70, 72, 100, 108, 111, 118, 122, 124, 130, 131, 136, 137, 138, 143, 144, 169, 170, 171, 175, 178, 180, 183, 184, 191, 202]
            # 100WTC
            # CC_wsis: [1, 3, 6, 7, 8, 11, 12, 13, 14, 15, 39, 40, 42, 43, 52, 53, 54, 55, 67, 70, 71, 72, 88, 91, 95, 100, 108, 109, 111, 118, 122, 124, 130, 131, 135, 136, 137, 138, 143, 144, 145, 167, 168, 169, 170, 171, 173, 174, 175, 178, 179, 180, 183, 184, 185, 189, 191, 192, 202, 204, 206, 207, 208, 215, 217, 222, 223, 224, 225, 226, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 263, 264, 265, 266, 269, 275, 276, 277, 291, 296, 297, 298, 299, 300, 325, 328, 329, 330, 374, 375]
            # small testing
            # CC_wsis: [2, 41, 69, 90, 110, 123, 134, 177, 190, 201]
            # large testing
            # CC_wsis: [146, 158, 163, 164, 165, 363, 373, 376, 377, 378, 379, 380, 390, 391, 392, 400, 401, 402, 406, 407, 408, 409, 410, 422, 454, 455, 459, 460, 461, 468, 469, 470, 471, 472, 474, 475, 476, 483, 484]
            # empty
            # CC_wsis: []
            
            classes : [0, 1, 2]

            old_HCC_shift_map:
                0: [0, 0]
                1: [-15, 10]
                2: [0, 0]

            # trainer
            num_trial: 4
            data_num: 3200
            num_wsi: 40

            backbone: "ViT" # efficient / ViT
            pretrain: False
            
            test_model: "self" # self / multi / 3_class_40WTC /3_class_100WTC
            test_state: "new"
            test_type: "CC"
            test_model_trial: 0
            test_model_wsis: []

            min_epoch: 30
            max_epoch: 30
            max_notImprove: 2
            ema_decay: 0.999

            batch_size: 32
            base_lr: 1e-5

            flip_mode: "connect"
            area_thresh: 20
            
            # dataset
            error_rate: 0
            load_dataset: False
            data_trial: 0

            HCC_old_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/Old_HCC_WSI_rawdata"
            # HCC_old_ndpi_path: "/media/ipmclab-2/WSI Files/Old_HCC_WSI_rawdata"
            HCC_new_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/New_HCC_WSI_rawdata"
            # HCC_new_ndpi_path: "/media/ipmclab-2/WSI Files/New_HCC_WSI_rawdata"
            HCC_old_patches_save_path: "/media/ipmclab-2/HDD8T/Data/DB_Backup/DB/Unbalenced"
            HCC_new_patches_save_path: "/media/ipmclab-2/HDD8T/HCC_Patch"
            HCC_csv_dir: "/home/ipmclab-2/project/Results/HCC_NDPI/Data_Info"
            HCC_WTC_result_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI"
            HCC_generation_save_path: "/home/ipmclab-2/project/Results/HCC_NDPI/Generation_Training"
            
            CC_ndpi_path: "/home/ipmclab-2/project/Data/ndpi/CC_WSI_rawdata"
            # CC_ndpi_path : "/media/ipmclab-2/WSI Files/CC_WSI_rawdata"
            CC_patches_save_path: "/media/ipmclab-2/HDD8T/CC_Patch"
            CC_csv_dir : "/home/ipmclab-2/project/Results/CC_NDPI/Data_Info"
            CC_WTC_result_save_path: "/home/ipmclab-2/project/Results/CC_NDPI"
            CC_generation_save_path: "/home/ipmclab-2/project/Results/CC_NDPI/Generation_Training"
            
            Mix_WTC_result_save_path: "/home/ipmclab-2/project/Results/Mix_NDPI"
            Mix_generation_save_path: "/home/ipmclab-2/project/Results/Mix_NDPI/Generation_Training"

            40WTC_model_path: "/home/ipmclab-2/project/Results/Mix_NDPI/40WTC_Result/LP_6400/trial_2/Model/40WTC_LP6400_3_class_trial_2_Model.ckpt"
            100WTC_model_path: "/home/ipmclab-2/project/Results/Mix_NDPI/100WTC_Result/LP_3200/trial_1/Model/100WTC_LP3200_3_class_trial_1_Model.ckpt"